dist: trusty
sudo: required
language: node_js
node_js:
 - "8"
cache:
  directories:
    - node_modules
env:
  - AWS_ACCESS_KEY_ID="travis"
  - AWS_SECRET_ACCESS_KEY="travis"
install:
  - sudo apt-get install uuid-runtime
  - npm install
before_script:
  - bash auth/create-secret.sh
script:
  - npm run validate
